### ISSUE TITLE
Virus Prediction with My Bacterial Sequences

### ISSUE THREAD

**Issue by drob2727** [KennthShang/HostG#4]
Is it possible to predict the hosts with my own bacterial sequences so I can see which contig belongs to which prediction?

**Comment by KennthShang** [comment]
Yes,  of course.  please follow the guidelines ”database extension" to add your data

**Comment by drob2727** [comment]
When adding your own bacterial sequences do you have any suggestions on completion and contamination of the genome? For example could I have 5% contamination? I'm currently using 0% and I'm just curious.

**Comment by KennthShang** [comment]
Ummmm, Since I am a CS student, I am not really sure what is the meaning of contamination. Do you mean your genomes are assembled from metagenomic data and you do not know whether they are pure bacterial contigs? If so, I think the model can still give a prediction, as long as you tell the model they are bacterial contigs.

Best,
Jiayu
